image: openbsd/latest
sources:
  - https://git.sr.ht/~rkta/w3m
packages:
  - boehm-gc
  - gettext-tools
triggers:
  - action: email
    condition: always
    to: mail@rkta.de
environment:
  OPTS: '-Werror -Wno-invalid-source-encoding'
tasks:
  - default: |
      cd w3m
      make distclean || :
      ./configure
      make -j4
      test -x w3m
      cd t
      sh run
      cd -
      ./w3m -insecure -dump gemini://rkta.srht.site/w3m-gemini.gmi
